version: '3.8'

services:
  mysqldb:
     image: mysql:5.7
     restart: unless-stopped
     environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
       MYSQL_DATABASE: achatdb
     ports:
       - 3306:3306
     volumes:
       - db:/var/lib/mysql

#backendapp

  app_achat_backend:
     image: mohamedaliazouzi/achat
     restart: on-failure
     ports:
       - "8082:8082"
     depends_on:
       - mysqldb

     stdin_open: true
     tty: true

volumes:
  db:


#dockercomposechanges