version: '3.8'

services:
  mysqldb:
     image: mysql:5.7
     restart: unless-stopped
     container_name: achatsecteur-db
     ports:
       - "3306:3306"
     volumes:
       - db:/var/lib/mysql
     environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
       MYSQL_DATABASE: achat_db


  app_achat_backend:
     image: mohamedaliazouzi/achat
     restart: unless-stopped
     ports:
       - 8082:8082
     depends_on:
       - mysqldb
     environment:

       SPRING_DATASOURCE_URL: jdbc:mysql://achatsecteur-db:3306/achat_db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

       SPRING_DATASOURCE_USERNAME: root

       SPRING_DATASOURCE_PASSWORD:


volumes:
  db:


#dockercomposechanges