version: '3'

services:
  mysqldb:
     image: mysql:latest
     container_name: mysql_db
     environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
       MYSQL_DATABASE: achat_db
     ports:
       - "3306:3306"
     volumes:
       - ./data.sql:/docker-entrypoint-initdb.d/data.sql
     networks:
       - my-network
     restart: always

#backendapp

  app_achat_backend:
     image: mohamedaliazouzi/achat
     container_name: springboot_achat
     ports:
       - "8082:8089"
     depends_on:
       - mysqldb
     environment:

       SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/achat_db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

       SPRING_DATASOURCE_USERNAME: root

       SPRING_DATASOURCE_PASSWORD:

     networks:

       - my-network

     volumes:

       - ./backend-data:/app/data

     restart: always  # Add this line to enable automatic restart


     stdin_open: true
     tty: true

networks:

  my-network:


#dockercomposechanges